### ISSUE TITLE
LLL:EXT:cms is removed in TYPO3 v8

### ISSUE THREAD

**Issue by d3pendent** [helhum/gridelements#1]
in 
**gridelements/Configuration/TCA/Overrides/tt_content.php**
use 
`LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf`
instead of
`LLL:EXT:cms/locallang_ttc.xlf`

**Comment by helhum** [comment]
hum. this is just a very old fork I created for a pull request or something. Don't use it please!
